<a href="https://colab.research.google.com/github/khalil0fficial/mlzoomcamp/blob/main/Homework_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [68]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Dataset/CaliforniaHousingPrices.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

**Question 1**

What's the version of Pandas that you installed?

In [4]:
pd.__version__

'1.5.3'

**Question 2**

How many columns are in the dataset?

In [6]:
df.shape

(20640, 10)

In [7]:
num_cols = df.shape[1]
num_cols

10

**Question 3**

Which columns in the dataset have missing values?

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [28]:
df.isnull().sum() > 0

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

**Question 4**

How many unique values does the ocean_proximity column have?

In [32]:
# Unique values of ocean_proximity
df["ocean_proximity"].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [33]:
# to get the number, use nunique()
df["ocean_proximity"].nunique()

5

**Question 5**

What's the average value of the median_house_value for the houses located near the bay?

In [42]:
df[df["ocean_proximity"] == 'NEAR BAY']["median_house_value"].mean().round()

259212.0

**Question 6**



1.   Calculate the average of total_bedrooms column in the dataset.
2.   Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3.   Now, calculate the average of total_bedrooms again.
Has it changed?
4. Has it changed?



In [49]:
avg_total_bedrooms = df["total_bedrooms"].mean().round()
avg_total_bedrooms

538.0

In [50]:
df['total_bedrooms'].fillna(avg_total_bedrooms, inplace=True)

As shown below, the mean of total_bedrooms has not changed after filling the missing values

In [55]:
avg_total_bedrooms_after_filling_missing_vals = df["total_bedrooms"].mean().round()
avg_total_bedrooms_after_filling_missing_vals

538.0

**Question 7**



1.   Select all the options located on islands.
2.   Select only columns housing_median_age, total_rooms, total_bedrooms.
3.   Get the underlying NumPy array. Let's call it X.
4.   Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5.   Compute the inverse of XTX.
6.   Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?



In [56]:
df["ocean_proximity"].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [63]:
df_island = df[df["ocean_proximity"]== "ISLAND"]
df_island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [65]:
df_island = df_island[["housing_median_age", "total_rooms", "total_bedrooms"]]
df_island

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [66]:
df_island.shape

(5, 3)

In [79]:
X = np.array(df_island)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [80]:
X.shape

(5, 3)

In [81]:
# Transpose X

TX = X.T
TX

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [82]:
TX.shape

(3, 5)

In [83]:
XTX = TX.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [84]:
XTX.shape

(3, 3)

In [85]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [86]:
y.shape

(5,)

In [87]:
# Inverse of XTX
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [88]:
inv_XTX.shape

(3, 3)

In [92]:
w = np.dot(np.dot(inv_XTX, TX), y)
w

array([23.12330961, -1.48124183,  5.69922946])

What's the value of the last element of w?

In [93]:
w[-1]

5.699229455065586